### ISSUE TITLE
diagrama de clases: carlos gatica osorio 

### ISSUE THREAD

**Issue by carlos0716c** [SistemasTecTlaxiaco/diagrama-de-clases#1]
[practica de architect.pdf](https://github.com/SistemasTecTlaxiaco/diagrama-de-clases/files/12570914/practica.de.architect.pdf)

**Comment by saul19bautista** [comment]
Buen trabajo 19/20
👍👍👍👍

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
